version: '3.4'

services:
  serviceheft.server:
    image: ${DOCKER_REGISTRY-}serviceheftserver
    build:
      context: .
      dockerfile: ServiceHeft.Server/Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.aspnet/https:/https:ro
